[project]
name = "security-scanner-analyzers"
version = "0.1.0"
description = "A collection of security scanner analyzers"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.5",
]
