name: Publish Python Package to PyPI

on:
  release:
    types: [published]   # Runs when a new GitHub Release is published

permissions:
  contents: read
  id-token: write  # Required for OIDC authentication

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Uses OIDC — no need to provide a token
          repository-url: https://upload.pypi.org/legacy/
