name: Publish Python Package to PyPI

on:
  release:
    types: [published]   # Runs when a new GitHub Release is published

permissions:
  contents: read
  id-token: write  # Required for OIDC authentication

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: build and publish to PyPI using OIDC and uv
        run: |
          uv build
          uv publish --trusted-publishing always
